### ISSUE TITLE
springcloud 多模块项目如何远程部署和热更新？

### ISSUE THREAD

**Issue by lcygames** [Liubsyy/HotSecondsIDEA#21]
springcloud 多模块项目和springboot以jar启动的项目如何远程部署和热更新？

**Comment by Liubsyy** [comment]
每一个需要热更新代码的模块，如果部署在不同服务器上（也有可能是同一服务器不同的java进程）都需要添加HotSecondsServer，如果是几个模块打包成一个服务，那就添加一个HotSecondsServer就行了，HotSecondsServer是嵌入到java进程单独开的端口单独的tcp/ip协议和客户端通信，总之，几个java进程就添加几个代理。springboot以fatjar形式运行可以支持远程热部署的，服务端启动进程后用HotSecondsClient连接即可，反正也能添加多组ip，另外热更新也不需要上传代码到jar里，热更新主要是替换内存里面的类，刷新内存中的缓存。
