### ISSUE TITLE
3.添加jvm参数

### ISSUE THREAD

**Issue by zhouguangyao** [Liubsyy/HotSecondsIDEA#24]
请问一下，这一步是添加在哪里呢？看起来像是本地项目启动参数。
==>
3.添加jvm参数
添加jvm参数开启热部署代理 -XXaltjvm=dcevm -javaagent:$path1/HotSecondsServer.jar=hotconf=$path2/hot-seconds-remote.xml
其中$path1是第1步上传的目录，$path2是第2步上传的目录

**Comment by Liubsyy** [comment]
本地和远程都支持的，不是main函数的args，它跟设置堆内存参数一样(比如-Xms, -Xmx)都是jvm参数，本地在IDEA里面就能添加: 运行类->Edit Configurations->Modify Options->Add VM options
![WX20230914-191813@2x](https://github.com/Liubsyy/HotSecondsIDEA/assets/132696548/75b30cca-17e3-4e74-a37a-85d86e9eb8b8)
