### ISSUE TITLE
Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by hhhhhzj** [Liubsyy/HotSecondsIDEA#25]
Mac系统部署启动时报错: Symbol not found: ____chkstk_darwin， 
Referenced from: /Users/hzjdemac/IdeaProjects/pai/HotSecondsServer-future2/lib/boot.dylib (which was built for Mac OS X 10.15)

查了下是我的系统版本太低了10.13.6， 很早的笔记本已经不支持升级到最新版本了。应该有不少这样的用户了吧，能否打一个低版本的包

**Comment by Liubsyy** [comment]
用Mac10.12打包了一版，看看行不行，我这边试了下没问题了，如果没问题的话后续Mac版本都以10.12为最低版本
[boot.dylib](https://github.com/Liubsyy/HotSecondsIDEA/releases/download/fast_track/boot.dylib)

**Comment by hhhhhzj** [comment]
可以了，非常感谢
