### ISSUE TITLE
咨询下Spring的热部署更新问题

### ISSUE THREAD

**Issue by hhhhhzj** [Liubsyy/HotSecondsIDEA#27]
想请教下Spring框架下是咋解决依赖更新的？在Spring启动的时候记录下来bean的依赖关系么？

**Comment by Liubsyy** [comment]
bean的依赖是由Spring统一管理的，热更新只是通过BeanDefinitionRegistry中移除bean，再通过registerBeanDefinition注册bean的定义，最后Spring就可以根据定义重新创建bean了
