### ISSUE TITLE
IDEA 2023.2 更新18.8之后启动报错，排除HotSecondsClient-1.8.8.jar之后正常启动

### ISSUE THREAD

**Issue by AlbertJason** [Liubsyy/HotSecondsIDEA#35]
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/28864818/5aab60b9-043a-4729-89be-4c0fbeeda35c)

**Comment by Liubsyy** [comment]
试了下仅仅IDEA2023.2安装1.8.8有问题，我过滤了一下版本，你再更新一下就没问题了，应该是能更新到1.8.7

**Comment by AlbertJason** [comment]
好的，正常了
