### ISSUE TITLE
热部署插件在控制台打印的日志怎么配置debug模式，想看一下热部署失败的原因

### ISSUE THREAD

**Issue by jimmie0204** [Liubsyy/HotSecondsIDEA#37]
<img width="1384" alt="iShot_2023-10-07_10 41 23" src="https://github.com/Liubsyy/HotSecondsIDEA/assets/15029541/499f1a54-4060-48b1-9ae7-6b7a7d73fe89">

**Comment by Liubsyy** [comment]
HotSecondsClient控制台只有客户端的日志，直接上服务器上可以看到失败的日志以及异常

**Comment by jimmie0204** [comment]
> HotSecondsClient控制台只有客户端的日志，直接上服务器上可以看到失败的日志以及异常

日志路径是啥呀，是HotSecondsServer单独的日志吗，还是自己服务的业务日志，还是jvm日志？

**Comment by Liubsyy** [comment]
后续的版本我有空加下这个，独立文件输出日志

**Comment by Liubsyy** [comment]
最新版已加上日志，输出hotseconds.log文件
