### ISSUE TITLE
Mybatis Mapper目录配置疑问

### ISSUE THREAD

**Issue by bin-z** [Liubsyy/HotSecondsIDEA#43]
### 目前仅在本机使用，但是这样配置Mapper.xml热部署不生效
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/25219512/9ab13238-16c3-49eb-a116-b9086fcc00b5)
热部署提示：
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/25219512/ae0dc12b-e5bc-47ec-a58f-960a5e5c4174)

### 项目结构如下
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/25219512/98ce799f-2203-43da-971e-003106d28997)
### biz依赖了service，Mapper.xml放在service模块里
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/25219512/8e2c8020-a57e-49bc-9419-eaf6c3ccada0)

目前Class可以热部署，Mapper.xml不能热部署，请问应该如何配置？

**Comment by Liubsyy** [comment]
因为这些术语和配置都是以远程热部署为标准的，$rootPath$是个变量，表示IDEA工程根目录，远程路径必须是绝对路径，你可以全部写本地绝对路径最简单，后面的Client版本我针对本地热部署简化一下配置

**Comment by bin-z** [comment]
感谢，使用绝对路径是可以的
ps：windows要使用“/”而不是"\"
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/25219512/99690874-a9b1-4b16-9bf9-659b33b641f7)



> 因为这些术语和配置都是以远程热部署为标准的，$rootPath$是个变量，表示IDEA工程根目录，远程路径必须是绝对路径，你可以全部写本地绝对路径最简单，后面的Client版本我针对本地热部署简化一下配置
