### ISSUE TITLE
请问 jdk本身是没有dcevm相关组件的吗   

### ISSUE THREAD

**Issue by Yy2311** [Liubsyy/HotSecondsIDEA#45]
我执行完sh install.sh后  执行java -XXaltjvm=dcevm -version报错 
Error: missing `dcevm' JVM at `/usr/local/java/jre/lib/aarch64/dcevm/libjvm.so'.
Please install or use the JRE or JDK that contains these missing components.
我们项目用的 jdk1.8_345.   是版本导致的吗。 
我们的项目是sass平台上做的，我们没有权限更改jdk版本 有解决方案吗。

**Comment by Yy2311** [comment]
我看 intall.sh  对181以上版本 是把libjvm.so 放到/jre/lib/amd64/dcevm/libjvm.so。但执行java -XXaltjvm=dcevm -version 时寻找的路径是 /jre/lib/aarch64/dcevm/libjvm.so 。我手动把libjvm.so 放到aarch64下面 还是不行会报错
Error: dl failure on line 898
Error: failed /usr/local/java/jre/lib/aarch64/dcevm/libjvm.so, because /usr/local/java/jre/lib/aarch64/dcevm/libjvm.so: cannot open shared object file: No such file or directory

**Comment by Liubsyy** [comment]
试试这个行不行，路径用 /jre/lib/aarch64/dcevm/libjvm.so
[libjvm.so](https://github.com/Liubsyy/HotSecondsIDEA/releases/download/fast_track/libjvm.so)
