### ISSUE TITLE
远程热部署之后有一定概率导致服务挂掉

### ISSUE THREAD

**Issue by freedom727** [Liubsyy/HotSecondsIDEA#48]
远程热部署之后有一定概率导致服务挂掉，是因为jvm重新加载class文件时，接口有请求过来导致挂掉的吗
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/38785230/e279fbb3-56a4-4c45-8d91-7c79c2efa74a)

**Comment by freedom727** [comment]
目前出现了三次，都是在连续热部署了三四个文件之后出现的问题

**Comment by freedom727** [comment]
均采用本地编译然后热部署的形式

**Comment by Liubsyy** [comment]
是Java8吗，如果是的话看看jdk版本和libjvm.so是不是一致的

**Comment by freedom727** [comment]
open——jdk1.8.171，使用的是你提供的172版本

**Comment by freedom727** [comment]
[hs_err_pid15368.log](https://github.com/Liubsyy/HotSecondsIDEA/files/13361704/hs_err_pid15368.log)

**Comment by freedom727** [comment]
换成jre里面自带的libjvm.so没问题吧？
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/38785230/2d0de427-a282-401a-95ad-74a843753466)

**Comment by Liubsyy** [comment]
应该还是跟版本有一定关系，你能升级一下JDK版本吗，和so保持一个版本

**Comment by freedom727** [comment]
没办法升级，公司定制的系统，统一采用的这个版本的jdk，话说你提供的这个libjvm.so是在哪找的，我去找找对应版本的

**Comment by Liubsyy** [comment]
所有的版本都在里面了，你可以去 https://github.com/dcevm/dcevm/releases 看看。Linux环境谈不上升级不升级的，你可以自己弄一个沙盒环境或者镜像，专门用于远程热部署，使用特定版本的jdk
