### ISSUE TITLE
远程连接成功后热部署一直失败:hotswap xxx fail

### ISSUE THREAD

**Issue by freedom727** [Liubsyy/HotSecondsIDEA#49]
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/38785230/f6c1ac9c-69e3-4161-b357-c898917bc87f)
springboot项目，Classloader已检查
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/38785230/2e124639-1bcf-4759-b16a-8130d4959dd9)
昨天出现热部署导致服务挂掉的情况，所以今天换了一台服务器，重新将jdk8u171升级成jdk8u181，然后就遇到hotswap xxx fail情况，降级回jdk8u171仍不行
libjvm.so均检查过版本
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/38785230/fab80347-db88-4a15-b665-f0a5608bd4c6)

**Comment by freedom727** [comment]
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/38785230/18dd4eec-2d24-4cec-a27b-ca598b8046a4)
这是181的dcevm
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/38785230/10a2d192-9f5d-4c5e-b911-a2f5845f111c)
环境也没问题

**Comment by Liubsyy** [comment]
有异常日志吗，如果没有，可以在你的项目里加上System.setOut(new PrintStream(new FileOutputStream("hotseconds.log", true)))，然后看看hotseconds.log文件输出

**Comment by freedom727** [comment]
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/38785230/d5b18093-0cc0-4588-8461-5bb2d612cb27)

![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/38785230/5df0a676-2c78-4427-8bfa-c43122e52ba1)

**Comment by Liubsyy** [comment]
热部署插件支持加减方法的，没问题，你把jvm参数发一下，看看是不是没有加 -XXaltjvm=dcevm

**Comment by freedom727** [comment]
是的，真的忘记加了。。。
