### ISSUE TITLE
无法热部署新增静态内部类吗？

### ISSUE THREAD

**Issue by freedom727** [Liubsyy/HotSecondsIDEA#50]
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/38785230/3670a684-d67a-482c-885a-3ba6a19afa9b)
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/38785230/df494755-e1e2-4bc6-9edf-1af0b60a6d59)
日志能打印出来，但是调用接口就访问不到
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/38785230/7c33e8f8-d74a-4b4b-bf4f-a9b32a78c4d2)

**Comment by Liubsyy** [comment]
热更新无任何限制，包括内部类，很有可能是你本地的JDK版本和服务器存在差异，你试试远程编译并热部署

**Comment by freedom727** [comment]
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/38785230/ebb298b0-a6fe-44ad-980c-073f6755fab4)
试了下远程部署还是不行

**Comment by freedom727** [comment]
controller层打印的日志显示内部类又是新增成功了的，好奇怪

**Comment by Liubsyy** [comment]
那就是新增类成功了，但是springmvc返回的结果没有生效

**Comment by freedom727** [comment]
有办法解决吗，大佬

**Comment by Liubsyy** [comment]
当然可以解决，跟springmvc json序列化字段的缓存有关系，因为缓存你新加的字段没有被序列化，短期的方案你可以断点跟一下springmvc源码写一个扩展类清理一下缓存，往后HotSecondsExtetion项目会慢慢完善各种框架的缓存刷新

**Comment by Liubsyy** [comment]
springmvc新增字段json缓存清除，在HotSecondsExtension项目的1.0.1 版本中已优化
