### ISSUE TITLE
和jrebel这种付费插件有对比吗,能支持到什么程度?

### ISSUE THREAD

**Issue by shine10076** [Liubsyy/HotSecondsIDEA#51]
和jrebel的对比有吗

**Comment by Liubsyy** [comment]
分为两个层面，类热更新，第三方框架支持，前者都能支持，第三方框架支持没有jrebel多，支持常用的Spring, SpringBoot和Mybatis，你要是肯自己扩展的话，jrebel能做的一切，HotSeconds也能做，jrebel不支持的，HotSeconds也能支持，自己动手，丰衣足食！

**Comment by Liubsyy** [comment]
像一些公司内部自研的框架，国产框架，或者是一些非热门的框架，只有自定义扩展热更新逻辑，才能做到无死角热部署

**Comment by shine10076** [comment]
自定义扩展现在有详细文档说明吗

**Comment by Liubsyy** [comment]
简单的扩展：https://github.com/Liubsyy/HotSecondsIDEA/wiki/HotSeconds%E6%89%80%E6%9C%89%E5%8A%9F%E8%83%BD%E4%BB%8B%E7%BB%8D#27-%E6%8F%92%E4%BB%B6%E6%89%A9%E5%B1%95，也可以关注HotSecondsExtension项目
