### ISSUE TITLE
docker容器内会连接失败

### ISSUE THREAD

**Issue by lazysnake** [Liubsyy/HotSecondsIDEA#53]
如果使用nodeport方式暴露端口会报以下错误
![微信图片_20231122090715](https://github.com/Liubsyy/HotSecondsIDEA/assets/25835451/c0cfea36-1acd-4d50-a1a1-d3cb5237e429)
如果使用route路由，则能连接但是在热部署时会抛出异常
![微信图片_20231122095937](https://github.com/Liubsyy/HotSecondsIDEA/assets/25835451/496be18c-75d0-4889-a181-959ee34bb6a0)

**Comment by lazysnake** [comment]
内网环境，原谅我的门锁图片

**Comment by lazysnake** [comment]
HotSeconds版本是future3 Client是1.5.5，服务端是启动了的，端口也是通的

**Comment by Liubsyy** [comment]
第一种方式，本地->远程直连ip+端口测试过是通的对吧，远程服务器ip是10.128.9.130，配置文件hot-seconds.xml里面配的也是这个ip对吧，最后在服务器上hostname -i查看的ip也是这个，这三个都是一致的么？

**Comment by lazysnake** [comment]
> 第一种方式，本地->远程直连ip+端口测试过是通的对吧，远程服务器ip是10.128.9.130，配置文件hot-seconds.xml里面配的也是这个ip对吧，最后在服务器上hostname -i查看的ip也是这个，这三个都是一致的么？

这个ip 10.128.9.130 是容器内的ip，外面是无法访问的，配置的是宿主机的ip

**Comment by lazysnake** [comment]
nodeport方式是可以正常进行远程调试的

**Comment by Liubsyy** [comment]
现在是从远程获取注册服务是没问题的，但是获取到的服务是10.128.9.130:端口，但是你本地和容器ip是不通的所以无法通信，所以直接在server端添加jvm参数: -Djava.rmi.server.hostname=宿主机ip应该就行了，你可以试试

**Comment by Liubsyy** [comment]
现在是从远程获取注册服务是没问题的，但是获取到的服务是10.128.9.130:容器端口，但是你本地和容器ip是不通的所以无法通信，所以直接在server端添加jvm参数: -Djava.rmi.server.hostname=宿主机ip应该就行了，你可以试试，不过这样的话宿主机端口和映射容器端口得相同

**Comment by lazysnake** [comment]
> 现在是从远程获取注册服务是没问题的，但是获取到的服务是10.128.9.130:容器端口，但是你本地和容器ip是不通的所以无法通信，所以直接在server端添加jvm参数: -Djava.rmi.server.hostname=宿主机ip应该就行了，你可以试试，不过这样的话宿主机端口和映射容器端口得相同

这样改完后，就和route模式一样了，热部署timeout

**Comment by Liubsyy** [comment]
> > 现在是从远程获取注册服务是没问题的，但是获取到的服务是10.128.9.130:容器端口，但是你本地和容器ip是不通的所以无法通信，所以直接在server端添加jvm参数: -Djava.rmi.server.hostname=宿主机ip应该就行了，你可以试试，不过这样的话宿主机端口和映射容器端口得相同
> 
> 这样改完后，就和route模式一样了，热部署timeout

宿主机和docker端口都是一致的么？按这张方式的超时异常，点一下show balloon，把全部的异常发一下看看

**Comment by lazysnake** [comment]
> > > 现在是从远程获取注册服务是没问题的，但是获取到的服务是10.128.9.130:容器端口，但是你本地和容器ip是不通的所以无法通信，所以直接在server端添加jvm参数: -Djava.rmi.server.hostname=宿主机ip应该就行了，你可以试试，不过这样的话宿主机端口和映射容器端口得相同
> > 
> > 
> > 这样改完后，就和route模式一样了，热部署timeout
> 
> 宿主机和docker端口都是一致的么？按这张方式的超时异常，点一下show balloon，把全部的异常发一下看看

是一样的
![微信图片_20231122131007](https://github.com/Liubsyy/HotSecondsIDEA/assets/25835451/e47e6f87-0061-4536-b742-585b3ed43d3f)

**Comment by lazysnake** [comment]
刚刚又重新试了下，发现已经OK了，服务端提示 **HotDeployService热部署服务启动成功** 不代表已就绪？

**Comment by lazysnake** [comment]
远程编译并热部署此文件会出现以下异常
![7fed31c88d85229b6bf369626d64abf](https://github.com/Liubsyy/HotSecondsIDEA/assets/25835451/f0becf01-a5d0-4344-b95b-efaa9fa43946)
本地编译是没问题的

**Comment by Liubsyy** [comment]
> 远程编译并热部署此文件会出现以下异常 ![7fed31c88d85229b6bf369626d64abf](https://user-images.githubusercontent.com/25835451/284798734-f0becf01-a5d0-4344-b95b-efaa9fa43946.jpg) 本地编译是没问题的

远程是jdk还是jre启动的，看看JAVA_HOME/lib目录下是不是有tools.jar，有这个才能服务器才能支持运行时编译

**Comment by lazysnake** [comment]
> > 远程编译并热部署此文件会出现以下异常 ![7fed31c88d85229b6bf369626d64abf](https://user-images.githubusercontent.com/25835451/284798734-f0becf01-a5d0-4344-b95b-efaa9fa43946.jpg) 本地编译是没问题的
> 
> 远程是jdk还是jre启动的，看看JAVA_HOME/lib目录下是不是有tools.jar，有这个服务器才能支持运行时编译

确实没有这个，一些类似properties的配置文件能支持热部署吗？

**Comment by Liubsyy** [comment]
可以的，不过得自己写刷新逻辑， https://github.com/Liubsyy/HotSecondsIDEA/wiki/HotSeconds%E6%89%80%E6%9C%89%E5%8A%9F%E8%83%BD%E4%BB%8B%E7%BB%8D#27-%E6%8F%92%E4%BB%B6%E6%89%A9%E5%B1%95

**Comment by lazysnake** [comment]
> 可以的，不过得自己写刷新逻辑， https://github.com/Liubsyy/HotSecondsIDEA/wiki/HotSeconds%E6%89%80%E6%9C%89%E5%8A%9F%E8%83%BD%E4%BB%8B%E7%BB%8D#27-%E6%8F%92%E4%BB%B6%E6%89%A9%E5%B1%95

好的，非常感谢
