### ISSUE TITLE
master分支  编译报错

### ISSUE THREAD

**Issue by wgx1995** [Liubsyy/HotSecondsIDEA#55]
![636c2205-2987-41c9-898b-029d87852e98](https://github.com/Liubsyy/HotSecondsIDEA/assets/33681964/4c39c685-9421-429c-9472-99e0c30908b1)

**Comment by wgx1995** [comment]
想用源码编译  但是报错了

**Comment by Liubsyy** [comment]
用java11就能编译了，目标版本还是1.8
