### ISSUE TITLE
使用 java -jar 命令启动的工程能实现热部署吗？

### ISSUE THREAD

**Issue by GmerEmmer** [Liubsyy/HotSecondsIDEA#56]

**Comment by Liubsyy** [comment]
能

**Comment by GmerEmmer** [comment]
![48ee9904f4f04d18f7ec0491f0f6d8e](https://github.com/Liubsyy/HotSecondsIDEA/assets/100701632/e219f1c4-c57e-44a6-822d-9f6e8df15fc4)
我修改显示成功了，只是修改了代码，但是服务端并没有修改，有一条报错信息
![27bdd56ba4ec31622275deff29ab3c2](https://github.com/Liubsyy/HotSecondsIDEA/assets/100701632/9ca903d5-0c0e-4803-abe3-7ecf893c3e28)
这是什么原因？

**Comment by Liubsyy** [comment]
你用了web容器吗？你断点看看Class.forName("org.springframework.core.io.Resource").getClassLoader()是哪个

**Comment by GmerEmmer** [comment]
使用了 springboot，将类加载器修改为 LaunchedURLClassLoader 成功了。
