### ISSUE TITLE
匿名内部类可以实现热更吗

### ISSUE THREAD

**Issue by GmerEmmer** [Liubsyy/HotSecondsIDEA#57]
在方法中添加匿名内部类：
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/100701632/0ac92f96-5b63-4eba-a35b-c08a5838ea1d)
远程热更报错
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/100701632/4289e93a-8c96-48e1-90ad-8bc76562d5cd)

**Comment by Liubsyy** [comment]
再热一次就好了

**Comment by GmerEmmer** [comment]
没用，还是报了相同的错
